branch-defaults:
  master:
    environment: polymarket-bot-production
    group_suffix: null

global:
  application_name: polymarket-bot
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 22
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
