branch-defaults:
  master:
    environment: polymarket-bot-22-production
    group_suffix: null

global:
  application_name: polymarket-bot-22
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 22
  default_region: af-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
